using Microsoft.Win32;
using System.Windows.Media.Imaging;
using System.IO;
using System.Windows.Controls;
using System.Windows.Media;
using System.Net.Http;
using EzCollege.Models;

namespace EzCollege.Helpers
{
    public class Helper
    {
        public static BitmapImage GetBitmapImage()
        {
            OpenFileDialog openFileDialog = new();
            openFileDialog.Filter = "Image files (*.png;*.jpeg;*.jpg)|*.png;*.jpeg;*.jpg";
            openFileDialog.Multiselect = false;
            openFileDialog.FilterIndex = 1;
            if (openFileDialog.ShowDialog() == true)
            {
                return new BitmapImage(new Uri(openFileDialog.FileName));
            }
            return null!;
        }

        public static void ChangeTextColor(TextBlock textBlock, SolidColorBrush color)
        {
            textBlock.Foreground = color;
        }

        public static StreamContent ConvertImageToContent(BitmapSource image)
        {
            var stream = new MemoryStream();
            BitmapEncoder enc = new BmpBitmapEncoder();
            enc.Frames.Add(BitmapFrame.Create(image));
            enc.Save(stream);
            stream.Position = 0;

            return new StreamContent(stream);
        }


        public static GenChatResponseModel GenerateErrorGenChatResponseModel(
            string? model = null,
            string? provider = null,
            string? content = null
        )
        {
            Message message = new() { role = null, content = content! };
            Choices choices = new() { index = 0, message = message };
            GenChatResponseModel errorModel = new()
            {
                id = null,
                model = model,
                provider = provider,
                choices = [choices]
            };
            return errorModel;
        }

        public static string RemoveWaterMark(GenChatResponseModel genChatResponseModel)
        {
            string content = genChatResponseModel!.choices!.First().message!.content!;

            if (genChatResponseModel.provider!.Equals("Blackbox"))
            {
                string substringToRemove = "Generated by BLACKBOX.AI, try unlimited chat https://www.blackbox.ai";

                return content.Replace(substringToRemove, String.Empty);
            }

            return content;
        }
    }
}
